{
 "title": "Sample Python API Dashboard",
 "tags": [
  "python",
  "fastapi",
  "backstage"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}